package warehouse;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-05-02T12:51:40.670+02:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "IEmulatorService",
                  wsdlLocation = "file:/C:/Users/nikol/Documents/GitHub/SemestProject4/demo/src/main/java/warehouse/Service.asmx",
                  targetNamespace = "http://tempuri.org/")
public class IEmulatorService_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://tempuri.org/", "IEmulatorService");
    public static final QName BasicHttpBindingIEmulatorService = new QName("http://tempuri.org/", "BasicHttpBinding_IEmulatorService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/nikol/Documents/GitHub/SemestProject4/demo/src/main/java/warehouse/Service.asmx");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IEmulatorService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/nikol/Documents/GitHub/SemestProject4/demo/src/main/java/warehouse/Service.asmx");
        }
        WSDL_LOCATION = url;
    }

    public IEmulatorService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IEmulatorService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IEmulatorService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public IEmulatorService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IEmulatorService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IEmulatorService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IEmulatorService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEmulatorService")
    public IEmulatorService getBasicHttpBindingIEmulatorService() {
        return super.getPort(BasicHttpBindingIEmulatorService, IEmulatorService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEmulatorService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEmulatorService")
    public IEmulatorService getBasicHttpBindingIEmulatorService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIEmulatorService, IEmulatorService.class, features);
    }

}
