
package warehouse;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-05-02T12:51:40.618+02:00
 * Generated source version: 4.0.4
 *
 */
public final class IEmulatorService_BasicHttpBindingIEmulatorService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "IEmulatorService");

    private IEmulatorService_BasicHttpBindingIEmulatorService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IEmulatorService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        IEmulatorService_Service ss = new IEmulatorService_Service(wsdlURL, SERVICE_NAME);
        IEmulatorService port = ss.getBasicHttpBindingIEmulatorService();

        {
        System.out.println("Invoking insertItem...");
        int _insertItem_trayId = 0;
        java.lang.String _insertItem_name = "";
        java.lang.String _insertItem__return = port.insertItem(_insertItem_trayId, _insertItem_name);
        System.out.println("insertItem.result=" + _insertItem__return);


        }
        {
        System.out.println("Invoking pickItem...");
        int _pickItem_trayId = 0;
        java.lang.String _pickItem__return = port.pickItem(_pickItem_trayId);
        System.out.println("pickItem.result=" + _pickItem__return);


        }
        {
        System.out.println("Invoking getInventory...");
        java.lang.String _getInventory__return = port.getInventory();
        System.out.println("getInventory.result=" + _getInventory__return);


        }

        System.exit(0);
    }

}
